### ISSUE TITLE
RDSInstance cannot be deleted

### ISSUE THREAD

**Issue by hasheddan** [crossplane/stack-aws#138]
<!--
Thank you for helping to improve Crossplane!

Please be sure to search for open issues before raising a new one. We use issues
for bug reports and feature requests. Please find us at https://slack.crossplane.io
for questions, support, and discussion.
-->

### What happened?
<!--
Please let us know what behaviour you expected and how Crossplane diverged from
that behaviour.
-->

Statically created an `RDSInstance` that was provisioned successfully and reached steady state. On deletion, AWS returned error `InvalidParameterCombination: No modifications were requested` and refused to delete. Manually deleting in AWS console resulted in successful deletion and clean-up of Crossplane resource. 

### How can we reproduce it?
<!--
Help us to reproduce your bug as succinctly and precisely as possible. Artifacts
such as example manifests or a script that triggers the issue are highly
appreciated!
-->

Create an `RDSInstance` with the following configuration:
```yaml
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: rdsmysql
  labels:
    example: "true"
spec:
  forProvider:
    dbInstanceClass: db.t2.small
    masterUsername: masteruser
    allocatedStorage: 20
    engine: mysql
  writeConnectionSecretsToNamespace: crossplane-system
  providerRef:
    name: aws-provider
  reclaimPolicy: Delete
```

This is the late-initialized `spec`:
```yaml
 spec:                                                                                                                                                                                                            
    forProvider:                                                                                                                                                                                                   
      allocatedStorage: 20                                                                                                                                                                                         
      autoMinorVersionUpgrade: true                                                                                                                                                                                
      availabilityZone: us-west-2d                                                                                                                                                                                 
      backupRetentionPeriod: 0                                                                                                                                                                                     
      caCertificateIdentifier: rds-ca-2019                                                                                                                                                                         
      copyTagsToSnapshot: false                                                                                                                                                                                    
      dbInstanceClass: db.t2.small                                                                                                                                                                                 
      dbSubnetGroupName: default                                                                                                                                                                                   
      deletionProtection: false                                                                                                                                                                                    
      enableIAMDatabaseAuthentication: false                                                                                                                                                                       
      enablePerformanceInsights: false                                                                                                                                                                             
      engine: mysql                                                                                                                                                                                                
      engineVersion: 5.7.22                                                                                                                                                                                        
      licenseModel: general-public-license                                                                                                                                                                         
      masterUsername: masteruser                                                                                                                                                                                   
      monitoringInterval: 0                                                                                                                                                                                        
      multiAZ: false                                                                                                                                                                                               
      port: 0                                                                                                                                                                                                      
      preferredBackupWindow: 09:45-10:15                                                                                                                                                                           
      preferredMaintenanceWindow: wed:12:30-wed:13:00                                                                                                                                                              
      publiclyAccessible: true                                            
      storageEncrypted: false
      storageType: gp2        
      vpcSecurityGroupIds:                      
      - <redacted>                    
    providerRef:     
      name: aws-provider
    reclaimPolicy: Delete
```

After it reaches condition `Ready: True`, delete it. Error surfaces:
```yaml
- lastTransitionTime: "2020-02-25T16:48:18Z"                                                                                                                                                                   
      message: "delete failed: cannot modify RDS instance: InvalidParameterCombination:                                                                                                                            
        No modifications were requested\n\tstatus code: 400, request id: 9414996b-db29-40a9-9c0a-862bde997a43"                                                                                                     
      reason: Encountered an error during resource reconciliation                                                                                                                                                  
      status: "False"                                                                                                                                                                                              
      type: Synced  
```

### What environment did it happen in?
Crossplane version: v0.8.0
stack-aws version: v0.6.0
Kubernetes version: 1.14
Kubernetes distro: EKS

<!--
Include at least the version or commit of Crossplane you were running. Consider
also including your:

* Cloud provider or hardware configuration
* Kubernetes version (use `kubectl version`)
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift)
* OS (e.g. from /etc/os-release)
* Kernel (e.g. `uname -a`)
-->

**Comment by hasheddan** [comment]
Ref TODO: https://github.com/crossplane/stack-aws/blob/12b4b63972249afa4e098311e48ff3c9440360bd/pkg/controller/database/rdsinstance.go#L228

**Comment by hasheddan** [comment]
Ref TODO: https://github.com/crossplane/stack-aws/blob/12b4b63972249afa4e098311e48ff3c9440360bd/pkg/controller/database/rdsinstance.go#L228

**Comment by hasheddan** [comment]
Ref TODO: https://github.com/crossplane/stack-aws/blob/12b4b63972249afa4e098311e48ff3c9440360bd/pkg/controller/database/rdsinstance.go#L228

**Comment by muvaf** [comment]
I think my TODO was more related to having `deletionProtection: true` because in that case even if the user changes it to `false`, it won't matter since `Update` is never called when the deletion timestamp exists. See https://github.com/crossplane/crossplane-runtime/issues/59

**Comment by hasheddan** [comment]
This was solved by updating the config as follows:

```yaml
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: rdsmysql
  labels:
    example: "true"
spec:
  forProvider:
    dbInstanceClass: db.t2.small
    masterUsername: masteruser
    allocatedStorage: 20
    engine: mysql
    applyModificationsImmediately: true # this was added
    skipFinalSnapshotBeforeDeletion: true # this was added
  writeConnectionSecretsToNamespace: crossplane-system
  providerRef:
    name: aws-provider
  reclaimPolicy: Delete
```

This works because:
1. `applyModificationsImmediately: true` makes it such that RDS *will not* wait for the next maintenance window to apply changes. This was the source of the error described above.
2. When applying changes immediately, we must specify `skipFinalSnapshotBeforeDeletion`. If we do not, you will observe the following error from AWS:

```
- lastTransitionTime: "2020-02-25T17:44:02Z"     
    message: "delete failed: cannot delete RDS instance: InvalidParameterCombination:
      FinalDBSnapshotIdentifier is required unless SkipFinalSnapshot is specified.\n\tstatus
      code: 400, request id: 589d07eb-73e3-443b-9229-6700d363b5cc"
    reason: Encountered an error during resource reconciliation         
    status: "False"                   
    type: Synced   
```
